[context.production]
  command = "yarn build"
  # functions = "lambda" #  netlify-lambda reads this
  publish = "dist"
[context.deploy-preview]
  command = "yarn build"
  # functions = "lambda" #  netlify-lambda reads this
  publish = "public"