name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 4 * * 2' # 4am every Tuesday Morning
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          DAILY_NETLIFY_BUILD_URL: ${{ secrets.DAILY_NETLIFY_BUILD_URL }}
        run: curl -X POST -d '{}' $DAILY_NETLIFY_BUILD_URL